apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32000
      name: http
  selector:
    app: echo
  